import type { DiseaseFormDef } from './types';
import { checks, eyeField, followup, num, radio, score, section, text } from './helpers';

const cataract: DiseaseFormDef = {
  id: 'cataract',
  title: 'Cataract',
  shortTitle: 'Cataract',
  fields: [
    eyeField,
    section('2. Etiological risk analysis'),
    checks('ageRelated', 'A. Age-related (degenerative)', ['Senile cataract (>50 years)']),
    checks('metabolic', 'B. Metabolic / systemic causes', [
      'Diabetes mellitus',
      'Hypocalcaemia',
      'Galactosemia',
      'Hyperparathyroidism',
      'Chronic renal failure',
      'Malnutrition',
    ]),
    checks('drugInduced', 'C. Drug-induced cataract', [
      'Steroids (systemic / topical)',
      'Antipsychotics (e.g., phenothiazines)',
      'Amiodarone',
      'Chemotherapy agents',
    ]),
    checks('ocularCauses', 'D. Ocular causes', [
      'Uveitis',
      'High myopia',
      'Retinal disease (ARMD / DR)',
      'Previous ocular surgery',
    ]),
    checks('traumatic', 'E. Traumatic', [
      'Blunt trauma',
      'Penetrating injury',
      'Radiation exposure',
      'Electric injury',
    ]),
    checks('congenital', 'F. Congenital / developmental', [
      'Congenital cataract',
      'Family history',
      'Intrauterine infections',
    ]),
    checks('lifestyle', 'G. Lifestyle / environmental', [
      'Smoking',
      'UV exposure',
      'Alcohol',
      'Dehydration',
    ]),
    section('3. Symptoms (C/O)'),
    checks('symptoms', 'Symptoms', [
      'Gradual painless vision loss',
      'Glare / photophobia',
      'Night vision difficulty',
      'Monocular diplopia',
      'Frequent refraction change',
      'Second sight (index myopia)',
    ]),
    section('4. Visual function'),
    text('ucva', 'UCVA'),
    text('bcva', 'BCVA'),
    text('pinhole', 'Pinhole'),
    text('contrastSensitivity', 'Contrast sensitivity'),
    radio('glareTest', 'Glare test', ['Positive', 'Negative']),
    text('colourVision', 'Colour vision'),
    section('Symptom scoring (CSGS)'),
    score('scoreBlurring', 'A. Visual blurring (distance)', [
      { value: 0, label: '0 – Clear vision' },
      { value: 1, label: '1 – Mild blurring in dim light' },
      { value: 2, label: '2 – Moderate blurring affecting daily tasks' },
      { value: 3, label: '3 – Severe blurring / cannot recognize faces' },
    ]),
    score('scoreNear', 'B. Near vision difficulty', [
      { value: 0, label: '0 – No difficulty' },
      { value: 1, label: '1 – Needs more light / magnification' },
      { value: 2, label: '2 – Cannot read small print' },
      { value: 3, label: '3 – Cannot read at all' },
    ]),
    score('scoreGlare', 'C. Glare / light sensitivity', [
      { value: 0, label: '0 – None' },
      { value: 1, label: '1 – Mild discomfort in sunlight' },
      { value: 2, label: '2 – Strong glare from light/sun/headlights' },
      { value: 3, label: '3 – Avoids bright light completely' },
    ]),
    score('scoreColor', 'D. Color / contrast perception', [
      { value: 0, label: '0 – Normal' },
      { value: 1, label: '1 – Slight dullness of colors' },
      { value: 2, label: '2 – Yellow/brown tint noticeable' },
      { value: 3, label: '3 – Severe foggy or washed-out vision' },
    ]),
    score('scoreDisability', 'E. Functional disability', [
      { value: 0, label: '0 – Normal daily life' },
      { value: 1, label: '1 – Mild limitation (night driving, fine work)' },
      { value: 2, label: '2 – Needs assistance for some activities' },
      { value: 3, label: '3 – Dependent / major disability' },
    ]),
    num('csgsTotal', 'TOTAL CSGS SCORE', { unit: '0–15', min: 0, max: 15, step: 1 }),
    section('5. Slit lamp examination'),
    checks('lensMorphology', 'Lens morphology', [
      'Nuclear sclerosis',
      'Cortical spokes',
      'Posterior subcapsular cataract (PSC)',
      'Mixed',
    ]),
    checks('etiologyClues', 'Clinical clues to etiology', [
      'PSC',
      'Snowflake cataract',
      'Rosette cataract',
      'Complicated cataract → Uveitis',
    ]),
    section('6–7. Associated findings / fundus'),
    checks('associatedFindings', 'Associated ocular findings', [
      'Corneal status',
      'Anterior chamber depth',
      'Fundus: Visible',
      'Fundus: Not visible',
    ]),
    num('iop', 'IOP', { unit: 'mmHg', min: 0, step: 'any' }),
    checks('fundusStatus', 'Fundus status', ['Normal', 'DR', 'ARMD', 'Not visible → B-scan']),
    section('9–11. Classification & plan'),
    checks('classification', 'Classification', ['Immature', 'Mature', 'Hypermature']),
    checks('etiologicalDiagnosis', 'Etiological diagnosis', [
      'Age-related cataract',
      'Diabetic cataract',
      'Steroid-induced cataract',
      'Complicated cataract (uveitis)',
      'Traumatic cataract',
      'Metabolic cataract',
      'Congenital',
    ]),
    checks('surgicalIndication', 'Surgical indication', [
      'Visual disability',
      'Glare',
      'Fundus not visible',
      'Patient need',
    ]),
    checks('managementMedical', 'Management – medical / preventive', [
      'Control diabetes',
      'Stop / taper steroids',
      'Correct metabolic imbalance',
      'UV protection',
    ]),
    checks('redFlags', 'Red flags', [
      'Phacomorphic glaucoma',
      'Phacolytic glaucoma',
      'Uveitis',
      'Sudden pain',
    ]),
    followup('followUps', '14. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'vaRe', label: 'VA RE' },
      { key: 'vaLe', label: 'VA LE' },
      { key: 'contrast', label: 'Contrast' },
      { key: 'csgs', label: 'CSGS', inputType: 'number', min: 0, max: 15, step: 1 },
      { key: 'colorVision', label: 'Color vision' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const diabeticRetinopathy: DiseaseFormDef = {
  id: 'diabetic_retinopathy',
  title: 'Diabetic Retinopathy (DR)',
  shortTitle: 'Diabetic retinopathy',
  fields: [
    eyeField,
    section('2. Risk factors'),
    checks('diseaseRelated', 'A. Disease-related', [
      'Duration of diabetes (>5–10 years)',
      'Poor glycaemic control (HbA1c >7%)',
    ]),
    checks('systemic', 'B. Systemic', [
      'Hypertension',
      'Dyslipidaemia',
      'Obesity',
      'Anaemia',
      'Renal disease',
      'Pregnancy',
    ]),
    checks('lifestyle', 'C. Lifestyle', [
      'Smoking',
      'Alcohol use',
      'Sedentary lifestyle',
      'Poor sleep / stress',
    ]),
    checks('genetic', 'D. Genetic / demographic', [
      'Family history of diabetes',
      'Female sex predominance',
    ]),
    section('3. Symptoms'),
    checks('symptoms', 'Symptoms', [
      'Blurred vision',
      'Fluctuating vision',
      'Central vision loss',
      'Floaters (vitreous haemorrhage)',
      'Scotoma',
      'Distorted vision (maculopathy)',
    ]),
    section('4. Clinical fundus findings'),
    checks('npdr', 'NPDR features', [
      'Microaneurysms',
      'Dot & blot haemorrhages',
      'Flame-shaped haemorrhages',
      'Hard exudates (circinate pattern)',
      'Cotton wool spots',
    ]),
    checks('ischaemic', 'Ischaemic changes', [
      'Venous beading',
      'IRMA',
      'Capillary non-perfusion',
    ]),
    checks('pdr', 'PDR features', [
      'NVD',
      'NVE',
      'Vitreous haemorrhage',
      'Fibrovascular proliferation',
      'Tractional retinal detachment',
    ]),
    section('5. Visual function'),
    text('bcva', 'BCVA (Snellen / LogMAR)'),
    radio('amsler', 'Amsler grid', ['Normal', 'Distorted']),
    text('contrastSensitivity', 'Contrast sensitivity'),
    section('6. OCT findings (macula)'),
    checks('dme', 'Diabetic macular edema (DME)', [
      'Spongiform swelling',
      'Cystoid macular edema',
      'Subretinal fluid (SRF)',
    ]),
    num('cmt', 'Central macular thickness (CMT)', { unit: 'µm', min: 0, step: 1 }),
    text('intraretinalCysts', 'Intraretinal cysts (INL / OPL)'),
    radio('fovealContour', 'Foveal contour', ['Normal', 'Distorted']),
    radio('ellipsoidZone', 'Ellipsoid zone', ['Intact', 'Disrupted']),
    radio('elm', 'External limiting membrane', ['Intact', 'Disrupted']),
    checks('vitreoretinal', 'Vitreoretinal interface', [
      'Vitreomacular traction (VMT)',
      'Epiretinal membrane (ERM)',
      'Posterior hyaloid traction',
    ]),
    section('7–10. Staging & status'),
    checks('staging', 'Staging (ETDRS)', [
      'Mild NPDR',
      'Moderate NPDR',
      'Severe NPDR (4-2-1 rule)',
      'Very Severe NPDR',
      'Proliferative DR (PDR)',
    ]),
    checks('maculopathyType', 'Diabetic maculopathy type', [
      'Non-tractional DME',
      'Tractional DME',
      'Mixed type',
    ]),
    num('hba1c', 'HbA1c', { unit: '%', min: 0, max: 30, step: 0.1 }),
    text('bp', 'BP (mmHg)'),
    checks('systemicControl', 'Systemic control', [
      'Lipid profile abnormal',
      'Renal impairment present',
    ]),
    checks('treatmentHistory', 'Treatment history', [
      'Anti-VEGF injections',
      'Laser photocoagulation (focal / PRP)',
      'Intravitreal steroids',
      'Vitrectomy',
    ]),
    section('11–13. Diagnosis & management'),
    text('npdrPdrStage', 'NPDR / PDR stage'),
    radio('withDme', 'With DME', ['Yes', 'No']),
    radio('withTraction', 'With traction', ['Yes', 'No']),
    checks('managementMedical', 'Management – medical', [
      'Glycaemic control optimisation',
      'Blood pressure control',
      'Lipid management',
      'Anti-VEGF therapy',
      'Steroids (selected cases)',
    ]),
    checks('managementLaser', 'Laser / surgical', [
      'Focal laser',
      'Pan-retinal photocoagulation (PRP)',
      'Pars plana vitrectomy (PPV)',
    ]),
    checks('monitoring', 'Monitoring', [
      'OCT follow-up',
      'Fundus photography',
      'FFA if required',
    ]),
    checks('redFlags', 'Red flags', [
      'Vitreous haemorrhage',
      'Rapid vision loss',
      'Neovascular glaucoma',
      'Tractional retinal detachment',
      'Severe ischemia',
    ]),
    followup('followUps', '14. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'eye', label: 'Eye' },
      { key: 'va', label: 'VA' },
      { key: 'cmt', label: 'CMT', inputType: 'number', unit: 'µm', min: 0, step: 1 },
      { key: 'stage', label: 'NPDR/PDR stage' },
      { key: 'treatment', label: 'Treatment' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const armd: DiseaseFormDef = {
  id: 'armd',
  title: 'ARMD (Age-related Macular Degeneration)',
  shortTitle: 'ARMD',
  fields: [
    eyeField,
    radio('ageOver50', 'Age >50', ['Yes', 'No']),
    section('2. Risk factors'),
    checks('modifiable', 'A. Major modifiable', [
      'Smoking',
      'Poor diet (low greens / antioxidants)',
      'Excess sunlight exposure',
      'Obesity / BMI',
      'Low antioxidants',
      'Low Lutein & Zeaxanthin',
      'Low Omega 3',
      'High saturated fat intake',
    ]),
    checks('systemic', 'B. Systemic', ['Hypertension', 'Cardiovascular disease', 'Diabetes']),
    checks('ocularGenetic', 'C. Ocular / genetic', [
      'Family history of AMD',
      'Hyperopia',
      'Light-colored iris',
    ]),
    section('3. Symptoms'),
    checks('symptoms', 'Symptoms', [
      'Gradual vision loss',
      'Sudden vision loss',
      'Metamorphopsia (Amsler distortion)',
      'Central scotoma',
      'Difficulty reading',
    ]),
    section('4. Clinical fundus / OCT findings'),
    checks('drusen', 'Drusen', ['None', 'Hard', 'Soft', 'Pseudo']),
    checks('atrophicPathway', 'Atrophic pathway', ['Photoreceptor loss', 'Geographic atrophy']),
    checks('cnvm', 'Neovascular pathway – CNVM', [
      'Type 1',
      'Type 2',
      'Type 3',
      'Scarred out CNVM',
    ]),
    checks('pigmentChanges', 'Pigment changes', [
      'None',
      'Hyperpigmentation',
      'Hypopigmentation',
      'PED',
    ]),
    checks('ped', 'PED', ['Serous PED', 'Hemorrhagic PED', 'Fibro vascular PED']),
    checks('neovascularSigns', 'Neovascular signs', ['Disciform scar / Fibrotic scar']),
    checks('ffa', 'FFA findings (optional)', [
      'No leakage',
      'Classic CNV',
      'Occult CNV',
      'Blocked fluorescence (hemorrhage)',
    ]),
    section('7–10. Staging & management'),
    checks('staging', 'Staging', [
      'No AMD',
      'Early AMD',
      'Intermediate AMD',
      'Late AMD',
      'Geographic atrophy',
      'Neovascular AMD',
    ]),
    checks('dryAmd', 'Dry (non-exudative)', [
      'Drusen present',
      'No fluid',
      'No CNV',
      '± Geographic atrophy',
    ]),
    checks('wetAmd', 'Wet (exudative)', [
      'CNV present',
      'Fluid (sub/intraretinal)',
      'Hemorrhage',
      'PED',
    ]),
    text('dryStage', 'Dry AMD – stage'),
    text('wetStage', 'Wet AMD – stage'),
    checks('mgmtDry', 'Management – dry AMD', [
      'AREDS supplements',
      'Lifestyle advice',
      'Amsler grid',
    ]),
    checks('mgmtWet', 'Management – wet AMD', [
      'Anti-VEGF planned',
      'Urgent referral',
      'Follow-up OCT',
    ]),
    followup('followUps', 'Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'oct', label: 'OCT' },
      { key: 'stage', label: 'Stage' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const cme: DiseaseFormDef = {
  id: 'cme',
  title: 'CME (Cystoid Macular Edema)',
  shortTitle: 'CME',
  fields: [
    eyeField,
    section('2. Risk factors'),
    checks('modifiable', 'A. Major modifiable', [
      'Recent cataract surgery',
      'Poor glycemic control',
      'Chronic inflammation',
      'Prostaglandin analog use',
      'Post-operative complications',
      'High screen exposure',
    ]),
    checks('systemic', 'B. Systemic', [
      'Diabetes',
      'Hypertension',
      'Renal disease',
      'Autoimmune disease',
      'Dyslipidemia',
    ]),
    checks('ocular', 'C. Ocular / secondary', [
      'Uveitis',
      'Retinal vein occlusion (CRVO / BRVO)',
      'Diabetic retinopathy',
      'Epiretinal membrane (ERM)',
      'Vitreomacular traction (VMT)',
      'Previous ocular surgery',
    ]),
    section('3–4. Symptoms & visual function'),
    checks('symptoms', 'Symptoms', [
      'Gradual vision loss',
      'Blurred vision',
      'Metamorphopsia',
      'Central scotoma',
      'Micropsia',
      'Difficulty reading',
      'Altered colour perception',
    ]),
    text('bcva', 'BCVA (Snellen / LogMAR)'),
    radio('amsler', 'Amsler grid', ['Normal', 'Distorted']),
    text('contrastSensitivity', 'Contrast sensitivity'),
    text('colourVision', 'Colour vision'),
    section('5. Clinical fundus / OCT'),
    num('cmt', 'Central macular thickness (CMT)', { unit: 'µm', min: 0, step: 1 }),
    checks('cystoidSeverity', 'Cystoid changes – severity', ['None', 'Mild', 'Moderate', 'Severe']),
    checks('cystoidSize', 'Cystoid changes – size', ['Small', 'Large', 'Coalescent']),
    checks('cystLocation', 'Location', ['INL', 'OPL']),
    checks('fluid', 'Fluid', ['Intraretinal', 'Subretinal (SRF)']),
    radio('fovea', 'Fovea', ['Normal', 'Loss of foveal depression', 'Distorted']),
    radio('ellipsoidZone', 'Ellipsoid zone', ['Intact', 'Disrupted']),
    radio('elm', 'External limiting membrane', ['Intact', 'Disrupted']),
    checks('vmi', 'Vitreomacular interface', [
      'Normal',
      'Vitreomacular traction (VMT)',
      'Posterior vitreous detachment (PVD)',
      'Epiretinal membrane (ERM)',
    ]),
    checks('associated', 'Associated findings', [
      'Hard exudates',
      'Macular thickening',
      'RPE changes',
    ]),
    checks('ffa', 'FFA findings', [
      'No leakage',
      'Petaloid (flower-petal) leakage',
      'Diffuse leakage',
      'Capillary non-perfusion',
      'Blocked fluorescence',
    ]),
    section('6–11. Staging, diagnosis & plan'),
    checks('chronicity', 'Chronicity', ['Acute (<3 months)', 'Chronic (>3 months)']),
    checks('staging', 'Staging (OCT-based)', [
      'Mild (CMT < 350 µm)',
      'Moderate (350–500 µm)',
      'Severe (>500 µm)',
    ]),
    checks('classification', 'Classification', [
      'Diabetic CME',
      'Pseudophakic CME (Irvine-Gass)',
      'Uveitic CME',
      'RVO-related CME',
      'Tractional CME',
      'Drug-induced CME',
      'Idiopathic',
    ]),
    checks('treatmentHistory', 'Treatment history', [
      'Previous Anti-VEGF',
      'Steroid injection',
      'Laser photocoagulation',
      'Surgery',
    ]),
    text('cmeCause', 'CME – cause'),
    text('cmeStage', 'Stage'),
    checks('mgmtMedical', 'Management – medical', [
      'Topical NSAIDs',
      'Steroids (Topical / Periocular / Intravitreal)',
      'Anti-VEGF',
    ]),
    checks('etiologyControl', 'Etiology control', [
      'Blood sugar control',
      'Treat inflammation',
      'Stop causative drugs',
      'Manage vascular disease',
    ]),
    checks('monitoring', 'Monitoring', [
      'OCT follow-up',
      'Visual acuity monitoring',
      'Retina referral',
    ]),
    checks('redFlags', 'Red flags', [
      'Rapid vision drop',
      'Increasing CMT',
      'Non-resolving CME',
      'Suspected ischemia',
      'Tractional component',
    ]),
    followup('followUps', '13. Follow-up tracking', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'eye', label: 'Eye' },
      { key: 'va', label: 'VA' },
      { key: 'cmt', label: 'CMT', inputType: 'number', unit: 'µm', min: 0, step: 1 },
      { key: 'cysts', label: 'Cysts' },
      { key: 'srf', label: 'SRF', inputType: 'number', unit: 'µm', min: 0 },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

export const FORM_PART_1: DiseaseFormDef[] = [cataract, diabeticRetinopathy, armd, cme];
