import type { DiseaseFormDef } from './types';
import { area, checks, date, eyeField, followup, num, radio, section, text } from './helpers';

const hereditary: DiseaseFormDef = {
  id: 'hereditary_retinal_dystrophies',
  title: 'Hereditary Retinal Dystrophies',
  shortTitle: 'Hereditary dystrophies',
  fields: [
    eyeField,
    section('2. Genetic / history profile'),
    checks('inheritance', 'A. Inheritance', [
      'X-linked',
      'Autosomal Dominant',
      'Autosomal Recessive',
      'Sporadic',
    ]),
    checks('familyHistory', 'B. Family history', ['Positive', 'Negative', 'Consanguinity']),
    checks('ageOfOnset', 'C. Age of onset', [
      'Childhood',
      'Adolescence',
      'Early adulthood',
      'Late onset',
    ]),
    section('3–5. Symptoms & visual function'),
    checks('symptoms', 'Symptoms (key differentiation)', [
      'Night blindness (RP)',
      'Central vision loss (Stargardt / Cone dystrophy)',
      'Photophobia (Cone dystrophy)',
      'Metamorphopsia (Best)',
      'Peripheral vision loss (RP)',
      'Difficulty in bright light (Cone dysfunction)',
    ]),
    text('bcva', 'BCVA'),
    radio('colourVision', 'Colour vision', ['Normal', 'Reduced']),
    radio('darkAdaptation', 'Dark adaptation', ['Normal', 'Impaired']),
    checks('contrastSensitivity', 'Contrast sensitivity', ['Reduced']),
    checks('visualField', 'Visual field', [
      'Ring scotoma (RP)',
      'Central scotoma (Stargardt / Cone)',
      'Peripheral constriction',
      'Normal',
    ]),
    section('6. Fundus findings (pattern recognition)'),
    checks('rpFundus', 'RP', [
      'Bone spicule pigmentation',
      'Attenuated vessels',
      'Waxy disc',
    ]),
    checks('stargardtFundus', 'Stargardt / Fundus flavimaculatus', [
      'Beaten bronze macula',
      'Yellow-white flecks',
      'Macular atrophy',
    ]),
    checks('bestFundus', 'Best disease', [
      'Vitelliform (“egg yolk”) lesion',
      'Vitelliruptive stage',
      'Atrophic scar',
    ]),
    checks('coneRodFundus', 'Cone-rod dystrophy', [
      'Normal fundus',
      "Bull's-eye maculopathy",
    ]),
    checks('xlrsFundus', 'X-linked retinoschisis', [
      'Foveal schisis (stellate pattern)',
      'Peripheral schisis',
    ]),
    section('7–11. Investigations & classification'),
    checks('oct', 'OCT findings', [
      'Photoreceptor loss (RP)',
      'Outer retinal atrophy (Stargardt)',
      'Subretinal material (Best)',
      'Foveal schisis (Retinoschisis)',
      'CME (RP / others)',
    ]),
    checks('ffa', 'FFA findings', [
      'Dark choroid (Stargardt)',
      'No leakage (Retinoschisis)',
      'Patchy fluorescence (Cone dystrophy)',
    ]),
    checks('erg', 'ERG', [
      'Reduced rods (RP)',
      'Cone loss > rod loss (Cone-rod dystrophy)',
      'Normal (Stargardt – early)',
      'Negative ERG (Retinoschisis)',
    ]),
    radio('eog', 'EOG', ['Abnormal (Best disease)', 'Normal', 'Not done']),
    checks('classification', 'Classification (final clinical type)', [
      'Retinitis Pigmentosa',
      'Stargardt disease',
      'Fundus flavimaculatus',
      'Best disease',
      'Cone-rod dystrophy',
      'X-linked juvenile retinoschisis',
    ]),
    checks('differential', 'Differential diagnosis', [
      'ARMD',
      'CSCR',
      'CME',
      'Drug toxicity (chloroquine)',
      'Macular hole',
    ]),
    area('finalDiagnosis', '12. Final diagnosis'),
    checks('mgmtSupportive', 'Management – supportive', [
      'Low vision aids',
      'UV protection',
      'Lifestyle modification',
    ]),
    checks('mgmtSpecific', 'Disease-specific notes', [
      'Avoid Vitamin A (Stargardt)',
      'Genetic counseling',
      'Family screening',
    ]),
    checks('redFlags', 'Red flags', [
      'Rapid visual decline',
      'CNV development',
      'Severe CME',
      'Sudden central vision loss',
    ]),
    followup('followUps', '15. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'field', label: 'Field' },
      { key: 'oct', label: 'OCT' },
      { key: 'ergEog', label: 'ERG/EOG' },
      { key: 'diagnosis', label: 'Diagnosis' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const macularDystrophy: DiseaseFormDef = {
  id: 'macular_dystrophy',
  title: 'Macular Dystrophy (Stargardt + Best Disease)',
  shortTitle: 'Macular dystrophy',
  fields: [
    eyeField,
    section('2. Genetic / risk profile'),
    checks('inheritance', 'A. Inheritance pattern', [
      'Autosomal Recessive (Stargardt)',
      'Autosomal Dominant (Best disease)',
      'Sporadic',
      'Unknown',
    ]),
    checks('familyHistory', 'B. Family history', [
      'Positive',
      'Negative',
      'Consanguinity present',
    ]),
    checks('ageOfOnset', 'C. Age of onset', ['Childhood', 'Adolescence', 'Early adulthood']),
    section('3–5. Symptoms & fundus'),
    checks('symptoms', 'Symptoms (C/O)', [
      'Gradual central vision loss',
      'Difficulty reading',
      'Central scotoma',
      'Photophobia',
      'Colour vision disturbance',
      'Metamorphopsia (Best disease)',
    ]),
    text('bcva', 'BCVA (Snellen / LogMAR)'),
    radio('amsler', 'Amsler grid', ['Normal', 'Distorted']),
    radio('colourVision', 'Colour vision', ['Normal', 'Reduced']),
    checks('contrastSensitivity', 'Contrast sensitivity', ['Reduced']),
    checks('stargardtFundus', 'Stargardt disease', [
      '“Beaten bronze” macular appearance',
      'Yellow-white flecks (pisciform)',
      'Macular atrophy',
    ]),
    checks('bestFundus', 'Best disease (vitelliform)', [
      'Egg-yolk lesion (vitelliform stage)',
      'Pseudohypopyon stage',
      'Vitelliruptive (“scrambled egg”) stage',
      'Atrophic / cicatricial stage',
    ]),
    section('6–12. OCT, FFA & staging'),
    checks('octStargardt', 'OCT – Stargardt', [
      'Outer retinal atrophy',
      'Ellipsoid zone loss',
      'RPE thinning',
    ]),
    checks('octBest', 'OCT – Best disease', [
      'Subretinal hyperreflective material',
      'Vitelliform lesion',
      'Subretinal fluid (±)',
      'RPE detachment',
    ]),
    checks('ffa', 'FFA findings', [
      '“Dark choroid” (Stargardt)',
      'Window defects',
      'Leakage (late stages if CNV develops)',
    ]),
    radio('erg', 'ERG', ['Normal', 'Reduced']),
    radio('eog', 'EOG', ['Abnormal (Best disease – diagnostic)', 'Normal', 'Not done']),
    checks('stargardtClass', 'Classification – Stargardt', [
      'Early',
      'Fleck stage',
      'Atrophic stage',
    ]),
    checks('bestClass', 'Classification – Best disease', [
      'Stage 1: Pre-vitelliform',
      'Stage 2: Vitelliform',
      'Stage 3: Pseudohypopyon',
      'Stage 4: Vitelliruptive',
      'Stage 5: Atrophic',
    ]),
    checks('differential', 'Differential diagnosis', [
      'ARMD',
      'Central serous chorioretinopathy',
      'Macular hole',
      'Pattern dystrophy',
    ]),
    checks('diseaseStage', 'Disease stage', ['Early', 'Moderate', 'Advanced']),
    checks('finalDiagnosis', 'Final diagnosis', ['Stargardt disease', 'Best disease']),
    text('stageText', 'Stage'),
    checks('mgmtSupportive', 'Management – supportive', [
      'Low vision aids',
      'Sunglasses / UV protection',
      'Avoid excessive light exposure',
    ]),
    checks('mgmtMonitoring', 'Monitoring', [
      'OCT follow-up',
      'Visual acuity monitoring',
      'Fundus photography',
    ]),
    checks('mgmtGenetic', 'Genetic counseling', ['Family screening', 'Genetic advice']),
    checks('redFlags', 'Red flags', [
      'Rapid central vision loss',
      'CNV development',
      'Sudden visual distortion',
      'Subretinal hemorrhage',
    ]),
    followup('followUps', '15. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'oct', label: 'OCT' },
      { key: 'stage', label: 'Stage' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const retinalDegenerations: DiseaseFormDef = {
  id: 'retinal_degenerations',
  title: 'Retinal Degenerations',
  shortTitle: 'Retinal degenerations',
  fields: [
    eyeField,
    checks('classification', '2. Classification', [
      'Peripheral retinal degeneration',
      'Vitreoretinal degeneration',
      'Macular degeneration',
    ]),
    section('Section A – Peripheral retinal degenerations'),
    checks('peripheralSymptoms', '3. Symptoms', [
      'Asymptomatic',
      'Floaters',
      'Flashes',
      'Peripheral field loss',
    ]),
    checks('lattice', 'Lattice degeneration', [
      'Present',
      'Retinal thinning',
      'Holes present',
      'Pigment changes',
    ]),
    checks('snailTrack', 'Snail track degeneration', [
      'Snowflake appearance',
      'Peripheral patches',
    ]),
    checks('retinoschisis', 'Degenerative retinoschisis', [
      'Smooth elevated retina',
      'Immobile',
      'Absolute scotoma',
    ]),
    checks('whiteLesions', 'White lesions', [
      'White with pressure',
      'White without pressure',
    ]),
    checks('otherPeripheral', 'Other peripheral lesions', [
      'Focal pigment clumps',
      'Peripheral chorioretinal atrophy',
      'Microcystoid degeneration',
    ]),
    radio('rdRisk', '5. Risk of retinal detachment', ['Low', 'Moderate', 'High']),
    checks('peripheralMgmt', '6. Management', [
      'Observation',
      'Prophylactic laser',
      'Patient education (RD symptoms)',
    ]),
    section('Section B – Vitreoretinal degenerations'),
    checks('vrType', '7. Type', [
      'Wagner syndrome',
      'Stickler syndrome',
      'Favre-Goldmann syndrome',
    ]),
    checks('vitreous', 'Vitreous', ['Liquefied', 'Syneresis', 'Membranes']),
    checks('vrRetina', 'Retina', [
      'Lattice-like degeneration',
      'Retinoschisis',
      'Pigmentary changes',
      'Vessel attenuation',
    ]),
    checks('vrLens', 'Lens', ['Cataract', 'Ectopia lentis']),
    checks('systemicFeatures', '9. Systemic features', [
      'Joint abnormalities',
      'Facial abnormalities',
      'Hearing loss',
      'Cardiac issues',
    ]),
    checks('vrInvestigations', '10. Investigations', ['OCT', 'ERG', 'Genetic evaluation']),
    checks('vrRisk', '11. Risk', ['High RD risk', 'Bilateral involvement']),
    checks('vrMgmt', '12. Management', [
      'Regular monitoring',
      'RD prophylaxis',
      'Genetic counselling',
    ]),
    section('Section C – Macular degeneration (non-ARMD)'),
    checks('macularTypes', '13. Types', [
      'Myopic macular degeneration',
      'Degenerative macular changes',
    ]),
    checks('macularSymptoms', '14. Symptoms', [
      'Central vision loss',
      'Distortion',
      'Reduced contrast',
    ]),
    checks('macularFindings', '15. Clinical findings', [
      'RPE atrophy',
      'Pigment changes',
      'Choroidal thinning',
      'CNV',
    ]),
    checks('macularIx', '16. Investigations', ['OCT', 'FFA', 'Fundus photography']),
    checks('macularMgmt', '17. Management', [
      'Observation',
      'Anti-VEGF (if CNV)',
      'Visual rehabilitation',
    ]),
    text('peripheralDiag', 'Peripheral degeneration – type'),
    text('vrDiag', 'Vitreoretinal degeneration – type'),
    text('macularDiag', 'Macular degeneration – type'),
    checks('redFlags', '19. Red flags', [
      'New flashes / floaters',
      'Sudden vision drop',
      'Visual field defect',
      'Suspected retinal detachment',
    ]),
    followup('followUps', '20. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'peripheral', label: 'Peripheral findings' },
      { key: 'oct', label: 'OCT' },
      { key: 'risk', label: 'Risk' },
      { key: 'plan', label: 'Plan' },
    ]),
  ],
};

const rop: DiseaseFormDef = {
  id: 'retinopathy_of_prematurity',
  title: 'Retinopathy of Prematurity (ROP)',
  shortTitle: 'ROP',
  fields: [
    section('Section A – Neonatal / screening ROP'),
    text('babyName', 'Baby name (if different)'),
    date('dob', 'Date of birth'),
    num('pma', 'PMA', { unit: 'weeks', min: 0, max: 60, step: 1 }),
    checks('riskProfile', '2. Risk profile', [
      'GA < 32 weeks',
      'Birth weight < 1500 g',
      'Oxygen therapy',
      'NICU stay',
      'RDS / Sepsis / Asphyxia / Systemic shock / Metabolic acidosis',
      'Poor weight gain',
      'Vit E deficiency',
    ]),
    checks('zone', 'Zone', ['Zone I', 'Zone II', 'Zone III']),
    checks('stage', 'Stage', [
      'Stage 1 – Demarcation line',
      'Stage 2 – Ridge',
      'Stage 3 – Extraretinal fibrovascular proliferation',
      'Stage 4a – Subtotal RD (extrafoveal)',
      'Stage 4b – Subtotal RD (involving macula)',
      'Stage 5 – Total RD',
    ]),
    radio('plusDisease', 'Plus disease', ['Present', 'Absent']),
    num('clockHours', 'Extent', { unit: 'clock hours /12', min: 0, max: 12, step: 1 }),
    checks('ropClass', '4. Classification', [
      'No ROP',
      'Mild ROP',
      'Type 2 ROP',
      'Type 1 ROP',
      'Advanced ROP',
    ]),
    checks('screeningMgmt', '5. Management', [
      'Observe',
      'Laser photocoagulation',
      'Anti-VEGF',
      'Urgent referral',
    ]),
    text('followUpInterval', 'Follow-up interval note'),
    section('Section B – Chronic ROP'),
    checks('chronicHistory', '1. History', [
      'Prematurity history',
      'Previous ROP',
      'Laser / Injection / Surgery',
    ]),
    radio('fixation', 'Fixation', ['Central', 'Eccentric', 'Poor']),
    text('va', 'VA'),
    radio('nystagmus', 'Nystagmus', ['Yes', 'No']),
    radio('strabismus', 'Strabismus', ['Yes', 'No']),
    radio('cornea', 'Cornea', ['Clear', 'Opacity']),
    radio('ac', 'AC', ['Normal', 'Shallow']),
    radio('lens', 'Lens', ['Clear', 'Cataract']),
    num('iop', 'IOP', { unit: 'mmHg', min: 0, step: 'any' }),
    checks('retina', 'Retina', ['Attached', 'Partial RD', 'Total RD']),
    checks('rdType', 'RD type', ['Tractional', 'Combined']),
    checks('macula', 'Macula', ['Attached', 'Detached', 'Distorted']),
    checks('fibrosis', 'Fibrosis / sequelae', [
      'Dragged disc',
      'Dragged macula',
      'Retrolental membrane',
      'Folded retina',
    ]),
    checks('complications', 'Complications', [
      'High myopia',
      'Amblyopia',
      'Glaucoma',
      'Strabismus',
      'Hydrocephalus',
      'Cataract',
      'Corneal haze',
      'Visual field constriction',
      'Macular pigmentary changes',
    ]),
    checks('investigations', 'Investigations', ['B-scan', 'OCT (if possible)']),
    checks('functionalStatus', 'Functional status', [
      'Mild impairment',
      'Moderate',
      'Severe',
      'Blind',
    ]),
    area('finalDiagnosis', '8. Final diagnosis'),
    checks('chronicMgmt', '9. Management (chronic)', [
      'Vitrectomy',
      'RD repair',
      'Low vision aids',
      'Amblyopia therapy',
      'Glasses',
      'Glaucoma monitoring',
      'Refraction',
      'Strabismus monitoring',
    ]),
    checks('redFlags', '10. Red flags', [
      'Progressive RD',
      'Pain (glaucoma)',
      'Sudden drop vision',
    ]),
    followup('followUps', '11. Follow-up record', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'retina', label: 'Retina' },
      { key: 'iop', label: 'IOP', inputType: 'number', unit: 'mmHg', min: 0 },
      { key: 'plan', label: 'Plan' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

export const FORM_PART_3: DiseaseFormDef[] = [hereditary, macularDystrophy, retinalDegenerations, rop];
