import type { DiseaseFormDef } from './types';
import { checks, eyeField, followup, num, radio, section, text } from './helpers';

const hypertensive: DiseaseFormDef = {
  id: 'hypertensive_retinopathy',
  title: 'Hypertensive Retinopathy',
  shortTitle: 'Hypertensive retinopathy',
  fields: [
    eyeField,
    section('2. Risk factors'),
    checks('systemic', 'A. Systemic', [
      'Hypertension',
      'Poor BP control',
      'Renal disease',
      'Dyslipidaemia',
      'Diabetes',
    ]),
    num('htnDuration', 'Hypertension duration', { unit: 'years', min: 0, step: 1 }),
    checks('special', 'B. Special conditions', [
      'Pregnancy-induced hypertension',
      'Malignant hypertension',
      'Young patient (high vascular tone)',
      'Elderly (arteriosclerosis)',
    ]),
    section('3–4. Symptoms & visual function'),
    checks('symptoms', 'Symptoms (C/O)', [
      'Asymptomatic',
      'Blurred vision',
      'Sudden vision loss (malignant HTN)',
      'Headache / systemic symptoms',
    ]),
    text('bcva', 'BCVA'),
    text('visualFields', 'Visual fields'),
    section('5. Fundus findings'),
    checks('arteriolar', 'Arteriolar changes', [
      'Generalized narrowing',
      'Focal narrowing',
      'Increased tortuosity',
    ]),
    checks('reflex', 'Arteriolar reflex', [
      'Normal',
      'Broadening of reflex',
      'Copper wiring',
      'Silver wiring',
    ]),
    checks('avCrossing', 'A-V crossing changes', ["Salu's sign", 'Bonnet sign', 'Gunn sign']),
    checks('retinalLesions', 'Retinal lesions', [
      'Flame-shaped haemorrhages',
      'Cotton wool spots',
      'Hard exudates',
      'Macular star',
      'Microaneurysms',
    ]),
    checks('disc', 'Disc changes', ['Normal', 'Disc oedema (papilloedema)', 'Optic pallor (late)']),
    section('6–9. Classification & systemic status'),
    checks('choroidal', 'Choroidal involvement', [
      'Elsching spots',
      'Siegrist streaks',
      'RPE changes',
      'Serous retinal detachment',
    ]),
    checks('pathophysiology', 'Pathophysiology', [
      'Vasospasm',
      'Arteriosclerosis',
      'Increased vascular permeability',
      'Ischaemia',
    ]),
    checks('classification', 'Classification', [
      'Grade I – Mild arteriolar narrowing',
      'Grade II – Narrowing + AV nicking',
      'Grade III – + haemorrhages / exudates / CWS',
      'Grade IV – + papilloedema',
    ]),
    text('bp', 'BP (mmHg)'),
    checks('systemicStatus', 'Systemic status', [
      'Hypertensive crisis present',
      'Renal involvement',
      'Cardiovascular risk',
    ]),
    text('finalGrade', 'Hypertensive retinopathy – Grade'),
    checks('mgmtSystemic', 'Management – systemic', [
      'Blood pressure control',
      'Gradual BP reduction (avoid rapid drop)',
      'Risk factor control (lipids, renal)',
    ]),
    checks('mgmtOcular', 'Ocular monitoring', ['Fundus follow-up', 'OCT', 'Referral']),
    checks('redFlags', 'Red flags', [
      'Papilloedema',
      'Sudden vision loss',
      'Malignant hypertension',
      'Serous detachment',
      'Rapid progression',
    ]),
    followup('followUps', '13. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'bp', label: 'BP' },
      { key: 'va', label: 'VA' },
      { key: 'grade', label: 'Grade' },
      { key: 'fundus', label: 'Fundus' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const cscr: DiseaseFormDef = {
  id: 'cscr',
  title: 'Central Serous Chorioretinopathy (CSCR)',
  shortTitle: 'CSCR',
  fields: [
    eyeField,
    section('2. Risk factors'),
    checks('modifiable', 'A. Major modifiable', [
      'Psychological stress',
      'Sleep disturbance',
      'Steroid use (systemic / topical)',
      'Type A personality',
      'High screen exposure',
    ]),
    checks('systemic', 'B. Systemic', [
      'Hypertension',
      "Cushing's disease",
      'Systemic lupus',
      'Atherosclerosis',
    ]),
    checks('drugHormonal', 'C. Drug / hormonal', [
      'Steroids',
      'Psychiatric medications',
      'Hormonal imbalance (cortisol related)',
    ]),
    section('3–5. Symptoms & findings'),
    checks('symptoms', 'Symptoms (C/O)', [
      'Sudden painless vision loss',
      'Central scotoma',
      'Micropsia',
      'Metamorphopsia',
      'Blurred vision',
      'Altered colour perception',
    ]),
    text('bcva', 'BCVA (Snellen / LogMAR)'),
    radio('amsler', 'Amsler grid', ['Normal', 'Distorted']),
    checks('fundus', 'Clinical fundus findings', [
      'Subretinal fluid (SRF)',
      'Loss / distortion of foveal reflex',
      'RPE changes',
      'Yellow-gray elevation (PED)',
      'Pigmentary changes (chronic cases)',
    ]),
    section('6–7. OCT & FFA'),
    num('cmt', 'Central macular thickness (CMT)', { unit: 'µm', min: 0, step: 1 }),
    num('srfHeight', 'Subretinal fluid height (SRF)', { unit: 'µm', min: 0, step: 1 }),
    checks('octStructural', 'OCT structural', [
      'Dome-shaped neurosensory detachment',
      'Clear subretinal fluid',
    ]),
    radio('pedPresent', 'PED present', ['Yes', 'No']),
    radio('fovealContour', 'Foveal contour', ['Normal', 'Distorted']),
    radio('rpeStatus', 'RPE status', ['Normal', 'Defect']),
    num('choroidalThickness', 'Choroidal thickness (EDI)', { unit: 'µm', min: 0, step: 1 }),
    checks('ffa', 'FFA findings', [
      'Ink-blot pattern',
      'Smoke-stack pattern',
      'Mushroom / umbrella configuration',
    ]),
    section('8–13. Classification & plan'),
    checks('classification', 'Classification', [
      'Acute CSCR',
      'Chronic CSCR (>3 months)',
      'Recurrent CSCR',
      'Bullous CSCR',
    ]),
    checks('differential', 'Differential diagnosis', [
      'Optic pit maculopathy',
      'PCV (Polypoidal choroidal vasculopathy)',
      'Macular hole with detachment',
      'Choroidal tumor',
      'Pachychoroid spectrum',
    ]),
    checks('pathophysiology', 'Pathophysiology', [
      'Choroidal hyperpermeability',
      'Increased hydrostatic pressure',
      'RPE barrier dysfunction',
      'Sympathetic overactivity',
    ]),
    checks('treatmentHistory', 'Treatment history', [
      'Observation',
      'Laser photocoagulation',
      'Anti-VEGF',
      'PDT',
    ]),
    checks('management', 'Management plan', [
      'Observation (self-limiting)',
      'Stop steroids',
      'Stress reduction',
      'Laser / PDT (chronic)',
    ]),
    checks('redFlags', 'Red flags', [
      'Persistent SRF',
      'Recurrent episodes',
      'Vision drop ≥ 2 lines',
      'PED enlargement',
      'Chronic RPE atrophy',
    ]),
    followup('followUps', '14. Follow-up table (OCT)', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'eye', label: 'Eye' },
      { key: 'cmt', label: 'CMT', inputType: 'number', unit: 'µm', min: 0, step: 1 },
      { key: 'srf', label: 'SRF height', inputType: 'number', unit: 'µm', min: 0 },
      { key: 'ped', label: 'PED' },
      { key: 'rpe', label: 'RPE' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

const rvo: DiseaseFormDef = {
  id: 'retinal_vascular_occlusive',
  title: 'Retinal Vascular Occlusive Disorders',
  shortTitle: 'RAO / RVO',
  fields: [
    eyeField,
    section('Section A – Retinal artery occlusion (RAO)'),
    checks('raoPresentation', '2. Presentation', [
      'Sudden painless vision loss',
      'Amaurosis fugax history',
    ]),
    text('raoDuration', 'Duration (min / hrs)'),
    text('raoVa', 'VA'),
    radio('rapd', 'RAPD', ['Present', 'Absent']),
    checks('raoFundus', '4. Fundus signs', [
      'Pale retina',
      'Cherry red spot',
      'Arterial narrowing',
      'Cattle trucking',
      'Cilioretinal sparing',
      'Milky-white appearance',
    ]),
    checks('raoType', '5. Type', ['CRAO', 'BRAO', 'Cilioretinal occlusion']),
    checks('raoEtiology', '6. Etiology', [
      'Cholesterol emboli',
      'Calcium emboli',
      'Platelet-fibrin emboli',
      'Carotid disease',
      'Cardiac source',
      'GCA',
      'Hypercoagulable state',
      'Mechanical factors (raised IOP)',
      'Retinal arteritis / perivasculitis',
      'Thrombophilic / other disorders',
    ]),
    checks('raoEmergency', '7. Emergency management', [
      'Ocular massage',
      'Acetazolamide',
      'Mannitol',
      'AC tap',
      'Oxygen',
      'Urgent stroke referral',
    ]),
    checks('raoInvestigations', '8. Investigations', [
      'OCT',
      'FFA',
      'FAF',
      'Carotid Doppler',
      'ECG / Echo',
      'ESR / CRP',
    ]),
    section('Section B – Retinal vein occlusion (RVO)'),
    checks('rvoPresentation', '9. Presentation', [
      'Sudden / gradual vision loss',
      'Unilateral',
    ]),
    checks('rvoDiagnosis', '10. Diagnosis', ['CRVO', 'BRVO', 'Hemispheric']),
    checks('rvoType', '11. Type', ['Non-ischaemic', 'Ischaemic', 'Impending']),
    checks('rvoRisk', '12. Risk factors', [
      'HTN',
      'Diabetes',
      'Smoking',
      'Hyperlipidemia',
      'Hyperviscosity / blood disorders',
      'Vasculitis',
      'Local factors (raised IOP, orbital disease)',
    ]),
    checks('rvoSigns', '13. Clinical signs', [
      'Dilated veins',
      'Cotton wool spots',
      'Macular edema',
      'Disc edema',
      'Neovascularization',
    ]),
    checks('rvoIschaemia', '14. Ischaemia check', [
      'RAPD present',
      'Extensive hemorrhage',
      'Capillary non-perfusion',
    ]),
    checks('rvoInvestigations', '15. Investigations', [
      'OCT',
      'FFA',
      'FAF',
      'IOP',
      'Visual field',
    ]),
    checks('rvoMgmt', '16. Management', [
      'Anti-VEGF',
      'Steroid',
      'Grid laser',
      'PRP',
      'Vitrectomy',
      'HTN control',
      'DM control',
    ]),
    section('Section C – Chronic / late-stage'),
    checks('chronicHistory', '17. History', ['Previous RAO / RVO', 'Previous treatment']),
    text('chronicDuration', 'Duration'),
    text('chronicVa', 'VA'),
    checks('visualStatus', '18. Visual status', [
      'Stable',
      'Worsening',
      'Field defect',
      'RAPD',
    ]),
    checks('anteriorSegment', '19. Anterior segment', [
      'Cornea',
      'Rubeosis iridis',
      'Angle NV',
    ]),
    num('iop', 'IOP', { unit: 'mmHg', min: 0, step: 'any' }),
    checks('raoSequelae', 'RAO sequelae', [
      'Optic atrophy',
      'Attenuated arteries thread-like',
      'Retinal thinning',
    ]),
    checks('rvoSequelae', 'RVO sequelae', [
      'Venous sheathing',
      'Collaterals',
      'Chronic macular edema',
      'Pigment changes',
    ]),
    checks('neovascular', 'Neovascular', ['NVD', 'NVE', 'NVG']),
    checks('octChronic', '21. OCT', ['Retinal thinning', 'CME', 'SRF', 'ERM']),
    checks('finalDiagnosis', '22. Final diagnosis', [
      'Old CRAO',
      'Old BRAO',
      'Chronic CRVO',
      'Chronic BRVO',
      'NVG',
    ]),
    checks('mgmtChronic', '23. Management (chronic)', [
      'Anti-VEGF',
      'PRP',
      'IOP control',
      'Vitrectomy',
      'Low vision aids',
      'Refraction',
      'HTN / DM control',
      'Lipid control',
    ]),
    checks('redFlags', '24. Red flags', ['New NV', 'Rising IOP', 'Sudden drop', 'VH']),
    followup('followUps', '25. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'iop', label: 'IOP', inputType: 'number', unit: 'mmHg', min: 0 },
      { key: 'oct', label: 'OCT' },
      { key: 'nv', label: 'NV' },
      { key: 'plan', label: 'Plan' },
    ]),
  ],
};

const rp: DiseaseFormDef = {
  id: 'retinitis_pigmentosa',
  title: 'Retinitis Pigmentosa (RP)',
  shortTitle: 'Retinitis pigmentosa',
  fields: [
    eyeField,
    section('2. Genetic / risk profile'),
    checks('inheritance', 'A. Inheritance pattern', [
      'Sporadic',
      'Autosomal Dominant',
      'Autosomal Recessive',
      'X-linked',
      'Unknown',
    ]),
    checks('familyHistory', 'B. Family history', [
      'Positive',
      'Negative',
      'Consanguinity present',
    ]),
    checks('riskIndicators', 'C. Associated risk indicators', [
      'Childhood onset',
      'Progressive course',
      'Bilateral involvement',
    ]),
    section('3–5. Symptoms & visual function'),
    checks('symptoms', 'Symptoms (C/O)', [
      'Night blindness (Nyctalopia)',
      'Peripheral vision loss',
      'Tunnel vision',
      'Difficulty in dark adaptation',
      'Progressive visual loss',
      'Late central vision loss',
    ]),
    text('bcva', 'BCVA (Snellen / LogMAR)'),
    radio('darkAdaptation', 'Dark adaptation', ['Normal', 'Impaired']),
    radio('colourVision', 'Colour vision', ['Normal', 'Reduced']),
    checks('contrastSensitivity', 'Contrast sensitivity', ['Reduced']),
    checks('visualField', 'Visual field analysis', [
      'Ring scotoma',
      'Peripheral field constriction',
      'Tunnel vision',
      'Central island preserved',
    ]),
    section('6–8. Fundus, OCT & electrophysiology'),
    checks('classicTriad', 'Classic triad', [
      'Bone-spicule pigmentation',
      'Attenuated retinal arterioles',
      'Waxy pale optic disc',
    ]),
    checks('additionalFindings', 'Additional findings', [
      'RPE atrophy',
      'Choroidal sclerosis',
      'Cystoid macular edema (CME)',
      'Posterior subcapsular cataract',
    ]),
    checks('oct', 'OCT findings', [
      'Photoreceptor layer loss',
      'Ellipsoid zone disruption',
      'Outer retinal thinning',
      'CME',
      'Foveal structure preserved',
      'Foveal structure lost',
    ]),
    radio('erg', 'ERG', ['Reduced', 'Extinguished']),
    radio('eog', 'EOG', ['Abnormal', 'Normal', 'Not done']),
    section('9–14. Classification & plan'),
    checks('clinicalType', 'By clinical type', [
      'Typical RP',
      'RP sine pigmento',
      'Sectoral RP',
      'Pericentral RP',
      'Retinitis punctata albescens',
    ]),
    checks('functionalType', 'By functional type', [
      'Type I (Rod predominant)',
      'Type II (Rod + Cone involvement)',
    ]),
    checks('ocularAssoc', 'Associated – ocular', [
      'Myopia',
      'Glaucoma',
      'Keratoconus',
      'Cataract',
    ]),
    checks('systemicSyndromes', 'Associated – systemic syndromes', [
      'Usher syndrome',
      'Laurence-Moon-Biedl',
      'Refsum syndrome',
      'Cockayne syndrome',
      'Hallgren syndrome',
    ]),
    checks('diseaseStage', 'Disease stage', [
      'Early (night blindness only)',
      'Moderate (field loss)',
      'Advanced (tunnel vision)',
      'Late (central vision loss)',
    ]),
    text('rpType', 'RP – type'),
    text('rpStage', 'Stage'),
    checks('mgmtSupportive', 'Management – supportive', [
      'Low vision aids',
      'Vitamin A',
      'UV protection',
    ]),
    checks('mgmtMonitoring', 'Monitoring', [
      'Visual field follow-up',
      'OCT monitoring',
      'ERG (if needed)',
    ]),
    checks('mgmtGenetic', 'Genetic / counseling', [
      'Genetic counseling',
      'Family screening',
    ]),
    checks('redFlags', 'Red flags', [
      'Rapid central vision loss',
      'Severe CME',
      'Sudden visual drop',
      'Secondary glaucoma',
    ]),
    followup('followUps', '15. Follow-up table', [
      { key: 'date', label: 'Date & time', inputType: 'datetime' },
      { key: 'va', label: 'VA' },
      { key: 'field', label: 'Field' },
      { key: 'oct', label: 'OCT' },
      { key: 'erg', label: 'ERG' },
      { key: 'remarks', label: 'Remarks' },
    ]),
  ],
};

export const FORM_PART_2: DiseaseFormDef[] = [hypertensive, cscr, rvo, rp];
